server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
    - image/png
    - image/jpeg
    - image/jpg
    - text/html
    - application/javascript
    - text/css
    - application/octet-stream
    - application/json
spring:
  resources:
    chain:
      html-application-cache: true
      gzipped: true
      cache: false
      strategy:
        content:
          enabled: true
          paths: /**
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://150.109.103.224:3306/activiti_schema?useUnicode=true&characterEncoding=utf8
      username: activiti
      password: xdrcft5^
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.muiboot.*


      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123
        # IP白名单
        # allow: 127.0.0.1
        # IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  aop:
    proxy-target-class: true
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 1000Mb
  activiti:
    check-process-definitions: false
    jpa-enabled: false


mybatis:
  config-location: classpath:config/mybatis-config.xml
  # type-aliases扫描路径
  type-aliases-package: com.muiboot.activti.entity
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/**/*.xml
  property:
    order: BEFORE

#mappers 多个接口时逗号隔开
mapper:
  mappers: com.muiboot.core.mapper.MyMapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level: debug